runtime: python39
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: flask
  version: 1.1.2
- name: google-api-python-client
  version: 2.1.0
- name: google-auth
  version: 1.28.0
- name: google-api-python-client
  version: 2.1.0
- name: google-auth-httplib2
  version: 0.1.0